@startuml 

left to right direction 
 

actor Utilisateur 
actor Expediteur 
rectangle "Shamazon" as S{
    usecase "Passer une commande\n--\n **extension points** \n Commander Urgence" as UC1
    usecase "Commander Urgence" as UC2
    usecase "Authentifier" as UC3
    usecase "Expedier Commande" as UC4
}

Utilisateur --> UC1
UC1 <.. UC2 : <<Extend>>
UC1 ..> UC3 : <<Include>>

UC4 <-- Expediteur


@enduml